import {
    LayoutDashboard, BookOpen, Users, DollarSign,
    Settings, LogOut, PlusCircle, BarChart, MessageSquare,
    Bell, Star, Award, Search, Sparkles, Package,
    Cpu, GitBranch, Database, Globe, Map, Radio, Trophy,
    Smartphone, Calendar, Briefcase, GraduationCap,
    Zap, ShoppingBag, LayoutTemplate, Network, Code,
    Grid, Film, TrendingUp, Rocket, ClipboardList,
    PenTool, Video, Heart, FileText, Clock, BarChart3,
    Upload, ShieldCheck, Brain, Home, Compass, Monitor,
    User
} from 'lucide-react';

export const navConfigs = {
    student: [
        { icon: Home, label: 'Home', path: '/' },
        { icon: Compass, label: 'Browse', path: '/courses' },
        { icon: BookOpen, label: 'My Learning', path: '/my-learning' },
        { icon: Code, label: 'Playground', path: '/code-playground' }, // Fixed path
        // Expanded sidebar items
        { type: 'divider', label: 'Browse' },
        { icon: Grid, label: 'Categories', path: '/categories' },
        { icon: Users, label: 'Instructors', path: '/instructors' },
        { icon: Star, label: 'My Instructors', path: '/my-instructors' },
        { type: 'divider', label: 'Discovery' },
        { icon: Film, label: 'Shorts', path: '/reels' },
        { icon: Radio, label: 'Social Media', path: '/social' },
        { icon: TrendingUp, label: 'Trending', path: '/trending' },
        { icon: Globe, label: 'Discover', path: '/discover-sectors' },
        { type: 'divider', label: 'Futuristic' },
        { icon: Cpu, label: 'AI Assistant', path: '/ai-assistant' }, // Fixed path
        { icon: Brain, label: 'Neural Tutor', path: '/intelligent-tutor' },
        { icon: Brain, label: 'Interview Prep', path: '/intelligent-tutor/interview' },
        { icon: GitBranch, label: 'Learning Paths', path: '/learning-paths' },
        { icon: GitBranch, label: 'Skill Trees', path: '/skill-paths' },
        { icon: Database, label: 'Storage Vault', path: '/storage-vault' },
        { icon: Sparkles, label: 'Aura Quest', path: '/aura-quest' },
        { icon: Monitor, label: 'Meta Classroom', path: '/meta-classroom' },
        { type: 'divider', label: 'Ecosystem' },
        { icon: Users, label: 'Study Groups', path: '/study-groups' },
        { icon: Users, label: 'Mentorship', path: '/mentorship' },
        { icon: Calendar, label: 'Events', path: '/events' },
        { icon: GraduationCap, label: 'Alumni Network', path: '/alumni' },
        { type: 'divider', label: 'Career' },
        { icon: Briefcase, label: 'Career Center', path: '/career-center' },
        { icon: Briefcase, label: 'Hiring Channel', path: '/hiring' },
        { icon: Briefcase, label: 'Job Board', path: '/jobs' },
        { icon: Grid, label: 'Projects', path: '/projects' },
        { icon: Rocket, label: 'Bootcamps', path: '/bootcamps' },
        { type: 'divider', label: 'Learning' },
        { icon: Trophy, label: 'Achievements', path: '/achievements' },
        { icon: ClipboardList, label: 'Assignments', path: '/assignments' },
        { icon: PenTool, label: 'Practice', path: '/practice' },
        { icon: Video, label: 'Live Sessions', path: '/live' },
        { icon: Award, label: 'Certificates', path: '/certificates' },
        { icon: Trophy, label: 'Leaderboard', path: '/leaderboard' },
        { icon: Heart, label: 'Wishlist', path: '/wishlist' },
        { type: 'divider', label: 'Communication' },
        { icon: MessageSquare, label: 'Messages', path: '/messages' },
        { icon: MessageSquare, label: 'Community', path: '/community' },
        { icon: Bell, label: 'Announcements', path: '/announcements' },
        { icon: Bell, label: 'Notifications', path: '/notifications' },
        { type: 'divider', label: 'Account' },
        { icon: FileText, label: 'My Notes', path: '/my-notes' },
        { icon: Star, label: 'My Reviews', path: '/my-reviews' },
        { icon: Clock, label: 'Purchase History', path: '/purchase-history' },
        { icon: Package, label: 'Bundles', path: '/bundles' },
        { icon: Sparkles, label: 'Subscriptions', path: '/subscriptions' },
        { icon: Settings, label: 'Settings', path: '/profile' },
    ],
    instructor: [
        { icon: BarChart3, label: 'Dashboard', path: '/instructor/dashboard' },
        { icon: BookOpen, label: 'My Courses', path: '/instructor/courses' },
        { icon: Zap, label: 'Bootcamps', path: '/instructor/bootcamps' },
        { icon: ShoppingBag, label: 'Marketplace', path: '/instructor/marketplace' },
        // Expanded items
        { icon: Upload, label: 'Add Course', path: '/instructor/upload' },
        { type: 'divider', label: 'Management' },
        { icon: Users, label: 'My Students', path: '/instructor/students' },
        { icon: ClipboardList, label: 'Assignments', path: '/instructor/assignments' },
        { icon: Award, label: 'Assessments', path: '/instructor/assessments' },
        { icon: Star, label: 'Reviews', path: '/instructor/reviews' },
        { type: 'divider', label: 'Performance' },
        { icon: DollarSign, label: 'Earnings', path: '/instructor/earnings' },
        { icon: BarChart, label: 'Analytics', path: '/instructor/analytics' },
        { icon: TrendingUp, label: 'Promotions', path: '/instructor/promotions' },
        { type: 'divider', label: 'Communication' },
        { icon: Bell, label: 'Announcements', path: '/instructor/announcements' },
        { icon: MessageSquare, label: 'Messages', path: '/messages' },
        { icon: MessageSquare, label: 'Community Feed', path: '/community' },
        { type: 'divider', label: 'Social' },
        { icon: Radio, label: 'Social Media', path: '/social' },
        { icon: Video, label: 'Live Stream', path: '/instructor/live' },
        { type: 'divider', label: 'Tools' },
        { icon: PenTool, label: 'Articles', path: '/instructor/articles' },
        { icon: ClipboardList, label: 'Practice Exams', path: '/instructor/practice' },
        { icon: Award, label: 'Certificates', path: '/instructor/certificates' },
        { icon: Package, label: 'Course Bundles', path: '/instructor/bundles' },
        { icon: Database, label: 'Content Manager', path: '/instructor/content' },
        { type: 'divider', label: 'Expert Tools' },
        { icon: BarChart3, label: 'Advanced Analytics', path: '/instructor/analytics-advanced' },
        { icon: Briefcase, label: 'Hiring Channel', path: '/hiring' },
        { icon: Award, label: 'Licensing Hub', path: '/instructor/licensing' },
        { icon: Rocket, label: 'Bootcamp Manager', path: '/instructor/bootcamp-manager' },
        { icon: Users, label: 'Study Group Lead', path: '/instructor/study-groups' },
        { icon: Map, label: 'Path Creator', path: '/instructor/learning-paths' },
        { icon: Code, label: 'Code Challenges', path: '/instructor/code-challenges' },
        { icon: Calendar, label: 'Event Manager', path: '/instructor/events-manage' },
        { type: 'divider', label: 'Discovery' },
        { icon: Search, label: 'Browse Courses', path: '/courses' },
        { icon: Grid, label: 'Categories', path: '/categories' },
        { icon: TrendingUp, label: 'Trending', path: '/trending' },
        { icon: Globe, label: 'Discover', path: '/discover-sectors' },
        { type: 'divider', label: 'Career Management' },
        { icon: Briefcase, label: 'Job Board', path: '/jobs' },
        { icon: Grid, label: 'Projects Marketplace', path: '/projects' },
        { icon: Rocket, label: 'Bootcamp Hub', path: '/bootcamps' },
        { type: 'divider', label: 'Advanced Tools' },
        { icon: Cpu, label: 'AI Assistant', path: '/ai-assistant' },
        { icon: Brain, label: 'Neural Tutor', path: '/intelligent-tutor' },
        { icon: GitBranch, label: 'Skill Trees', path: '/skill-paths' },
        { icon: Database, label: 'Storage Vault', path: '/storage-vault' },
        { icon: Sparkles, label: 'Aura Quest', path: '/aura-quest' },
        { icon: Monitor, label: 'Meta Classroom', path: '/meta-classroom' },
        { type: 'divider', label: 'Account' },
        { icon: Smartphone, label: 'Mobile Sync', path: '/mobile-sync' },
        { icon: Bell, label: 'Notifications', path: '/notifications' },
        { icon: Settings, label: 'Profile Settings', path: '/instructor/settings' },
    ],
    superadmin: [
        { icon: BarChart3, label: 'Admin Dashboard', path: '/admin' },
        { icon: Users, label: 'Users', path: '/admin/users' },
        { icon: BookOpen, label: 'Courses', path: '/admin/courses' },
        { icon: ShieldCheck, label: 'Instructors', path: '/admin/instructors' },
        { icon: DollarSign, label: 'Payments', path: '/admin/payments' },
        { icon: Sparkles, label: 'Subscriptions', path: '/admin/subscriptions' },
        { type: 'divider', label: 'Content' },
        { icon: Bell, label: 'Announcements', path: '/admin/announcements' },
        { icon: Database, label: 'Content Manager', path: '/admin/content' },
        { icon: BarChart, label: 'Analytics', path: '/admin/analytics' },
        { icon: LayoutTemplate, label: 'White-Label', path: '/admin/white-label' },
        { icon: Calendar, label: 'Platform Events', path: '/admin/events-manage' },
        { type: 'divider', label: 'Shared' },
        { icon: Briefcase, label: 'Global Jobs', path: '/jobs' },
        { icon: Users, label: 'Mentorship Hub', path: '/mentorship' },
        { icon: Smartphone, label: 'Mobile Sync', path: '/mobile-sync' },
        { type: 'divider', label: 'System' },
        { icon: Settings, label: 'Settings', path: '/admin/settings' },
    ]
};
